server:
  port: 8989
  tomcat:
    keep-alive-timeout: 120000
    connection-timeout: 120000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&serverTimeZone=Asia/Taipei
    username: ${DATABASE_MYSQL_USERNAME}
    password: ${DATABASE_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  application:
    name: Aki Chou Blog Admin Application
  data:
    redis:
      host: ${REDIS_HOST}
      password:
      port: 6379
      database: 0
      connect-timeout: 10000
      repositories:
        enabled: false

springdoc:
  api-docs:
    enabled: true
    path: /swagger
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: com.akichou

minio:
  url: ${OSS_MINIO_URL}
  access:
    name: ${OSS_MINIO_ACCESS_NAME}
    secret: ${OSS_MINIO_ACCESS_SECRET}
  bucket:
    name: aki-blog

logging:
  file:
    name: aki-admin-app.log
  level:
    root: info
